FROM node:18-slim

RUN npm install -g pnpm

WORKDIR /app

# We don't need the standalone Chromium
ENV PUPPETEER_SKIP_DOWNLOAD true
# Install chromium
RUN apt-get update \
 && apt-get install -y chromium \
    fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
    --no-install-recommends

# Install node depndencies
COPY package*.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .